name: 'My GitHub Action'
description: 'An example GitHub Action that echoes a message'
author: 'Your Name <your.email@example.com>'
inputs:
  message:
    description: 'The message to echo'
    required: true
    default: 'Hello, World!'
outputs:
  echo-output:
    description: 'The echoed message'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  color: 'blue'
  icon: 'megaphone'